//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ambulance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ambulanceEntities : DbContext
    {
        public ambulanceEntities()
            : base("name=ambulanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ambulance_user> ambulance_user { get; set; }
        public DbSet<doctors> doctors { get; set; }
        public DbSet<historystr> historystr { get; set; }
        public DbSet<ill_history> ill_history { get; set; }
        public DbSet<m_sister> m_sister { get; set; }
        public DbSet<palata> palata { get; set; }
        public DbSet<role> role { get; set; }
        public DbSet<pcount> pcount { get; set; }
        public DbSet<retir> retir { get; set; }
        public DbSet<retir1> retir1 { get; set; }
        public DbSet<retir2> retir2 { get; set; }
        public DbSet<retire> retire { get; set; }
    }
}
