//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ambulance
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctors
    {
        public doctors()
        {
            this.historystr = new HashSet<historystr>();
            this.ill_history = new HashSet<ill_history>();
        }
    
        public long shifr { get; set; }
        public string d_name { get; set; }
        public long OtdNumb { get; set; }
        public System.DateTime Date_in { get; set; }
        public System.DateTime Date_out { get; set; }
        public string Spec { get; set; }
    
        public virtual ICollection<historystr> historystr { get; set; }
        public virtual ICollection<ill_history> ill_history { get; set; }
    }
}
