//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ambulance
{
    using System;
    using System.Collections.Generic;
    
    public partial class historystr
    {
        public long Str_id { get; set; }
        public System.DateTime Date { get; set; }
        public long ill_id { get; set; }
        public long dshifr { get; set; }
    
        public virtual doctors doctors { get; set; }
        public virtual ill_history ill_history { get; set; }
    }
}
