//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ambulance
{
    using System;
    using System.Collections.Generic;
    
    public partial class palata
    {
        public palata()
        {
            this.ill_history = new HashSet<ill_history>();
        }
    
        public long Pal_id { get; set; }
        public long Places { get; set; }
        public long Free_places { get; set; }
        public long OtdNumb { get; set; }
    
        public virtual ICollection<ill_history> ill_history { get; set; }
    }
}
