//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ambulance
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public role()
        {
            this.ambulance_user = new HashSet<ambulance_user>();
        }
    
        public long role_id { get; set; }
        public string role_name { get; set; }
        public string role_password { get; set; }
    
        public virtual ICollection<ambulance_user> ambulance_user { get; set; }
    }
}
